# Generated by Django 4.0.4 on 2022-06-27 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characteristics', '0003_alter_characteristic_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('time', models.TimeField(verbose_name='Таймер')),
            ],
            options={
                'verbose_name': 'Правило',
                'verbose_name_plural': 'Правила',
            },
        ),
        migrations.CreateModel(
            name='RuleCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(choices=[('lt', 'Меньше значения'), ('gt', 'Больше значения'), ('equals', 'Равно значению')], max_length=32, verbose_name='Выражение')),
                ('value', models.CharField(max_length=32, verbose_name='Значение')),
                ('characteristic', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='characteristics.characteristic', verbose_name='Характеристика')),
                ('rule', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='notifications.rule', verbose_name='Правило')),
            ],
            options={
                'verbose_name': 'Описание правила',
                'verbose_name_plural': 'Описания правил',
            },
        ),
        migrations.AddConstraint(
            model_name='rulecharacteristic',
            constraint=models.UniqueConstraint(fields=('rule', 'characteristic'), name='unique_rule_characteristic'),
        ),
    ]
