# Generated by Django 4.0.4 on 2022-06-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristic',
            name='show_in_menu',
            field=models.BooleanField(default=False, verbose_name='Отображать в меню'),
        ),
    ]
