# Generated by Django 4.0.4 on 2022-06-24 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arenas', '0002_arena_title'),
        ('telegrambot', '0003_friendship_unique_user_friend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('datetime', models.DateTimeField(verbose_name='Дата')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, upload_to='polls/', verbose_name='Фото')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='arenas.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
            },
        ),
        migrations.CreateModel(
            name='UserPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('poll', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='polls.poll', verbose_name='Опрос')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='telegrambot.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответы пользователя',
                'verbose_name_plural': 'Ответы пользователей',
            },
        ),
        migrations.CreateModel(
            name='PollVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст')),
                ('poll', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='polls.poll', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
            },
        ),
    ]
