# Generated by Django 4.0.4 on 2022-07-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollvariant',
            name='is_open',
            field=models.BooleanField(default=False, verbose_name='Требует развернутого ответа'),
        ),
    ]
