# Generated by Django 4.0.4 on 2022-07-01 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_pollvariant_is_open'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
