# Generated by Django 4.0.4 on 2022-07-04 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arenas', '0003_remove_arena_photo_arenaphoto'),
        ('polls', '0003_alter_poll_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollvariant',
            name='is_open',
        ),
        migrations.AddField(
            model_name='poll',
            name='is_open',
            field=models.BooleanField(default=False, verbose_name='Требует развернутого ответа'),
        ),
        migrations.AddField(
            model_name='poll',
            name='is_start',
            field=models.BooleanField(default=False, verbose_name='Выводится при регистрации'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='city',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='arenas.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='datetime',
            field=models.DateTimeField(verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='description',
            field=models.TextField(verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Техническое название'),
        ),
    ]
