# Generated by Django 4.0.4 on 2022-07-04 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arenas', '0003_remove_arena_photo_arenaphoto'),
        ('polls', '0004_remove_pollvariant_is_open_poll_is_open_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='arenas.city', verbose_name='Город'),
        ),
    ]
