# Generated by Django 4.0.4 on 2022-06-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arenas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arena',
            name='title',
            field=models.CharField(default='-', max_length=32, verbose_name='Название манежа'),
            preserve_default=False,
        ),
    ]
