# Generated by Django 4.0.4 on 2022-07-04 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arenas', '0002_arena_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arena',
            name='photo',
        ),
        migrations.CreateModel(
            name='ArenaPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='arenas/', verbose_name='Фото')),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='arenas.arena', verbose_name='Манеж')),
            ],
            options={
                'verbose_name': 'Фото манежа',
                'verbose_name_plural': 'Фото манежей',
            },
        ),
    ]
