# Generated by Django 4.0.4 on 2022-06-01 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arenas', '0001_initial'),
        ('telegrambot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата')),
                ('max_players', models.PositiveIntegerField(verbose_name='Количество мест')),
                ('price', models.PositiveIntegerField(verbose_name='Стоимость участия')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('is_over', 'Закончена'), ('canceled', 'Отменена')], max_length=32, verbose_name='Статус')),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='arenas.arena', verbose_name='Манеж')),
                ('players', models.ManyToManyField(blank=True, to='telegrambot.telegramuser', verbose_name='Игроки')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
    ]
