# Generated by Django 4.0.4 on 2022-06-11 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0001_initial'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
        migrations.CreateModel(
            name='TelegramUserGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('signed_up', 'Записался'), ('confirmed', 'Подтвердил'), ('refused', 'Отказался')], max_length=32, verbose_name='Статус')),
                ('game', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='games.game', verbose_name='Игра')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='telegrambot.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Игра пользователя',
                'verbose_name_plural': 'Игры пользователей',
            },
        ),
    ]
