# Generated by Django 4.0.4 on 2022-06-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_game_players_telegramusergame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='max_players',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество мест'),
        ),
    ]
