# Generated by Django 4.0.4 on 2022-06-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_max_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramusergame',
            name='status',
            field=models.CharField(choices=[('signed_up', 'Записался'), ('confirmed', 'Подтвердил'), ('refused', 'Отказался')], default='signed_up', max_length=32, verbose_name='Статус'),
        ),
    ]
