# Generated by Django 4.0.4 on 2022-06-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_telegramusergame_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='send_t',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Старт уведомлений'),
        ),
    ]
