# Generated by Django 4.0.4 on 2022-06-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_send_t'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rule_n',
            field=models.IntegerField(blank=True, null=True, verbose_name='Получат уведомления'),
        ),
    ]
