# Generated by Django 4.0.4 on 2022-07-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_rule_n'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramusergame',
            name='status',
            field=models.CharField(choices=[('signed_up', 'Записался'), ('confirmed', 'Подтвердил'), ('reserve', 'В резерве'), ('refused', 'Отказался')], default='signed_up', max_length=32, verbose_name='Статус'),
        ),
    ]
