# Generated by Django 4.0.4 on 2022-07-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_telegramusergame_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('recruitment_done', 'Набор закончен'), ('is_over', 'Закончена'), ('canceled', 'Отменена')], max_length=32, verbose_name='Статус'),
        ),
    ]
