# Generated by Django 4.0.4 on 2022-07-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_game_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='level',
            field=models.CharField(choices=[('Новичок', 'Новичок'), ('Средний', 'Средний'), ('Высокий', 'Высокий')], max_length=32, verbose_name='Уровень игры'),
        ),
    ]
