# Generated by Django 4.0.4 on 2022-06-01 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arenas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, verbose_name='Имя пользователя')),
                ('telegram_username', models.CharField(max_length=128, verbose_name='Telegram')),
                ('phone_number', models.CharField(max_length=32, verbose_name='Номер телефона')),
                ('telegram_img', models.ImageField(blank=True, upload_to='users/', verbose_name='Фото')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('telegram_id', models.CharField(max_length=16, verbose_name='Telegram ID')),
                ('is_banned', models.BooleanField(default=False, verbose_name='Статус блокировки')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arenas.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
