# Generated by Django 4.0.4 on 2022-06-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0003_friendship_unique_user_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='notifications',
            field=models.BooleanField(default=True, verbose_name='Уведомления'),
        ),
    ]
