# Generated by Django 4.0.4 on 2022-07-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0004_telegramuser_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Telegram'),
        ),
    ]
