# Generated by Django 4.0.4 on 2022-06-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playtime', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayoftheweek',
            options={'ordering': ('id',), 'verbose_name': 'День недели', 'verbose_name_plural': 'Дни недели'},
        ),
        migrations.AlterModelOptions(
            name='usertime',
            options={'ordering': ('day_of_the_week', 'time'), 'verbose_name': 'Время', 'verbose_name_plural': 'Время'},
        ),
        migrations.AlterField(
            model_name='dayoftheweek',
            name='title',
            field=models.CharField(max_length=32, unique=True, verbose_name='День недели'),
        ),
    ]
