# Generated by Django 4.0.4 on 2022-06-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='RU', max_length=16, verbose_name='Язык справочника')),
                ('reg_phone_number', models.CharField(max_length=128, verbose_name='Запрос номера телефона')),
                ('reg_username', models.CharField(max_length=128, verbose_name='Запрос имени и фамилии')),
                ('reg_date_of_birth', models.CharField(max_length=128, verbose_name='Запрос даты рождения')),
                ('reg_city', models.CharField(max_length=128, verbose_name='Запрос города')),
                ('reg_level', models.CharField(max_length=128, verbose_name='Запрос уровня игры')),
                ('reg_playtime', models.CharField(max_length=128, verbose_name='Запрос времени игры')),
            ],
            options={
                'verbose_name': 'Справочник',
                'verbose_name_plural': 'Справочники',
            },
        ),
    ]
