# Generated by Django 4.0.4 on 2022-06-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='btn_friends',
            field=models.CharField(default='-', max_length=128, verbose_name='Кнопка "Друзья"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='btn_future_games',
            field=models.CharField(default='-', max_length=128, verbose_name='Кнопка "Предстоящие игры"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='btn_my_games',
            field=models.CharField(default='-', max_length=128, verbose_name='Кнопка "Мои игры"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='btn_notifications',
            field=models.CharField(default='-', max_length=128, verbose_name='Кнопка "Уведомления"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='btn_profile',
            field=models.CharField(default='-', max_length=128, verbose_name='Кнопка "Профиль"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='error_date_of_birth',
            field=models.CharField(default='-', max_length=128, verbose_name='Ошибка даты рождения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='error_phone_number',
            field=models.CharField(default='-', max_length=128, verbose_name='Ошибка номера телефона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='error_username',
            field=models.CharField(default='-', max_length=128, verbose_name='Ошибка имени и фамилии'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='play_skill_params',
            field=models.CharField(default='-', max_length=128, verbose_name='Уровни игры'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='time_select_emoji',
            field=models.CharField(default='-', max_length=128, verbose_name='Эмодзи (выбрано)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='time_unselect_emoji',
            field=models.CharField(default='-', max_length=128, verbose_name='Эмодзи (не выбрано)'),
            preserve_default=False,
        ),
    ]
