# Generated by Django 4.0.4 on 2022-06-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledges', '0002_knowledge_btn_friends_knowledge_btn_future_games_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='error_city',
            field=models.CharField(default='-', max_length=128, verbose_name='Ошибка города'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='success_reg',
            field=models.TextField(default='-', verbose_name='Успешная регистрация'),
            preserve_default=False,
        ),
    ]
