# Generated by Django 4.0.4 on 2022-06-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledges', '0003_knowledge_error_city_knowledge_success_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='btn_back_menu',
            field=models.CharField(default='-', max_length=128, verbose_name='Кнопка "Назад в меню"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='btn_edit_city',
            field=models.CharField(default='-', max_length=128, verbose_name='Кнопка "Изменить город"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='btn_edit_date_of_birth',
            field=models.CharField(default='-', max_length=128, verbose_name='Кнопка "Изменить дату рождения"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='btn_edit_level',
            field=models.CharField(default='-', max_length=128, verbose_name='Кнопка "Изменить уровень игры"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='btn_edit_name',
            field=models.CharField(default='-', max_length=128, verbose_name='Кнопка "Изменить имя"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='btn_edit_phone',
            field=models.CharField(default='-', max_length=128, verbose_name='Кнопка "Изменить телефон"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='btn_edit_playtime',
            field=models.CharField(default='-', max_length=128, verbose_name='Кнопка "Изменить удобное время"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='edit_message_text',
            field=models.CharField(default='-', max_length=128, verbose_name='Сообщение "Редактирование профиля"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='menu_message_text',
            field=models.CharField(default='-', max_length=128, verbose_name='Сообщение "Главное меню"'),
            preserve_default=False,
        ),
    ]
