# Generated by Django 4.0.4 on 2022-06-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledges', '0004_knowledge_btn_back_menu_knowledge_btn_edit_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='btn_search_about',
            field=models.CharField(default='-', max_length=32, verbose_name='Кнопка "О манеже"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='btn_search_enter',
            field=models.CharField(default='-', max_length=32, verbose_name='Кнопка "Записаться"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='btn_search_next',
            field=models.CharField(default='-', max_length=32, verbose_name='Кнопка "Далее"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='msg_games_empty',
            field=models.CharField(default='-', max_length=64, verbose_name='Сообщение о конце поиска'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='btn_back_menu',
            field=models.CharField(max_length=32, verbose_name='Кнопка "Назад в меню"'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='btn_edit_city',
            field=models.CharField(max_length=32, verbose_name='Кнопка "Изменить город"'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='btn_edit_date_of_birth',
            field=models.CharField(max_length=32, verbose_name='Кнопка "Изменить дату рождения"'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='btn_edit_level',
            field=models.CharField(max_length=32, verbose_name='Кнопка "Изменить уровень игры"'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='btn_edit_name',
            field=models.CharField(max_length=32, verbose_name='Кнопка "Изменить имя"'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='btn_edit_phone',
            field=models.CharField(max_length=32, verbose_name='Кнопка "Изменить телефон"'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='btn_edit_playtime',
            field=models.CharField(max_length=32, verbose_name='Кнопка "Изменить удобное время"'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='btn_friends',
            field=models.CharField(max_length=32, verbose_name='Кнопка "Друзья"'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='btn_future_games',
            field=models.CharField(max_length=32, verbose_name='Кнопка "Предстоящие игры"'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='btn_my_games',
            field=models.CharField(max_length=32, verbose_name='Кнопка "Мои игры"'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='btn_notifications',
            field=models.CharField(max_length=32, verbose_name='Кнопка "Уведомления"'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='btn_profile',
            field=models.CharField(max_length=32, verbose_name='Кнопка "Профиль"'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='edit_message_text',
            field=models.CharField(max_length=64, verbose_name='Сообщение "Редактирование профиля"'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='menu_message_text',
            field=models.CharField(max_length=64, verbose_name='Сообщение "Главное меню"'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='play_skill_params',
            field=models.CharField(max_length=64, verbose_name='Уровни игры'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='time_select_emoji',
            field=models.CharField(max_length=16, verbose_name='Эмодзи (выбрано)'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='time_unselect_emoji',
            field=models.CharField(max_length=16, verbose_name='Эмодзи (не выбрано)'),
        ),
    ]
