# Generated by Django 4.0.4 on 2022-06-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledges', '0005_knowledge_btn_search_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='btn_continue_time',
            field=models.CharField(default='-', max_length=32, verbose_name='Кнопка "Подтвердить время"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='friends_404_text',
            field=models.CharField(default='-', max_length=64, verbose_name='Друг не найден'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='friends_already_text',
            field=models.CharField(default='-', max_length=64, verbose_name='Ошибка "Друг уже добавлен"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='friends_btn_add',
            field=models.CharField(default='-', max_length=32, verbose_name='Кнопка "Принять приглашение"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='friends_btn_add_new',
            field=models.CharField(default='-', max_length=32, verbose_name='Кнопка "Добавить нового друга"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='friends_btn_decline',
            field=models.CharField(default='-', max_length=32, verbose_name='Кнопка "Отклонить приглашение"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='friends_enter_text',
            field=models.CharField(default='-', max_length=64, verbose_name='Запрос имени друга'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='friends_is_you_text',
            field=models.CharField(default='-', max_length=64, verbose_name='Ошибка "Себя добавить нельзя"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='friends_request_decline',
            field=models.CharField(default='-', max_length=64, verbose_name='Вы отклонили дружбу'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='friends_request_fall',
            field=models.CharField(default='-', max_length=64, verbose_name='Запрос дружбы отклонен'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='friends_request_text',
            field=models.CharField(default='-', max_length=64, verbose_name='Запрос дружбы отправлен'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='friends_send_text',
            field=models.CharField(default='-', max_length=64, verbose_name='Уведомление для друга'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='friends_text',
            field=models.CharField(default='-', max_length=64, verbose_name='Старт добавления друга'),
            preserve_default=False,
        ),
    ]
