# Generated by Django 4.0.4 on 2022-06-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledges', '0007_alter_knowledge_friends_404_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='friends_invite_msg',
            field=models.TextField(default='-', verbose_name='Сообщение для приглашения'),
            preserve_default=False,
        ),
    ]
