# Generated by Django 4.0.4 on 2022-06-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledges', '0008_knowledge_friends_invite_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='search_already_enter',
            field=models.CharField(default='-', max_length=64, verbose_name='Уже записан на игру'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='search_enter',
            field=models.CharField(default='-', max_length=64, verbose_name='Вы записались на игру'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='search_not_free_space',
            field=models.CharField(default='-', max_length=64, verbose_name='В игре нет мест'),
            preserve_default=False,
        ),
    ]
