# Generated by Django 4.0.4 on 2022-06-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledges', '0010_knowledge_edit_characteristic_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='btn_search_back',
            field=models.CharField(default='-', max_length=32, verbose_name='Кнопка "Назад"'),
            preserve_default=False,
        ),
    ]
