# Generated by Django 4.0.4 on 2022-06-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledges', '0011_knowledge_btn_search_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='my_games_cancel_btn',
            field=models.CharField(default='-', max_length=32, verbose_name='Кнопка "Отменить запись"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='my_games_cancel_text',
            field=models.CharField(default='-', max_length=64, verbose_name='Кнопка "Отменить запись"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='my_games_no_games',
            field=models.CharField(default='-', max_length=32, verbose_name='Вы не записаны на игры'),
            preserve_default=False,
        ),
    ]
