# Generated by Django 4.0.4 on 2022-06-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledges', '0013_alter_knowledge_my_games_cancel_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='notifications_delay',
            field=models.TimeField(default='14:10', verbose_name='Задержка после создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='notifications_end',
            field=models.TextField(default='14:10', verbose_name='Конец уведомлений'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='notifications_start',
            field=models.TextField(default='14:10', verbose_name='Старт уведомлений'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='language',
            field=models.CharField(default='RU', max_length=16, unique=True, verbose_name='Язык справочника'),
        ),
    ]
