# Generated by Django 4.0.4 on 2022-06-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledges', '0015_alter_knowledge_notifications_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='notifications_start',
            field=models.TimeField(verbose_name='Старт уведомлений'),
        ),
    ]
