# Generated by Django 4.0.4 on 2022-06-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledges', '0017_alter_knowledge_notifications_delay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledge',
            name='btn_notifications',
        ),
        migrations.AddField(
            model_name='knowledge',
            name='btn_notifications_off',
            field=models.CharField(default='-', max_length=32, verbose_name='Кнопка "Уведомления (отк.)"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='btn_notifications_on',
            field=models.CharField(default='-', max_length=32, verbose_name='Кнопка "Уведомления (вкл.)"'),
            preserve_default=False,
        ),
    ]
