# Generated by Django 4.0.4 on 2022-07-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledges', '0018_remove_knowledge_btn_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='polls_btn_cancel',
            field=models.CharField(default='-', max_length=32, verbose_name='Кнопка "Отменить"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='polls_btn_send',
            field=models.CharField(default='-', max_length=32, verbose_name='Кнопка "Отправить"'),
            preserve_default=False,
        ),
    ]
