# Generated by Django 4.0.4 on 2022-07-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledges', '0019_knowledge_polls_btn_cancel_knowledge_polls_btn_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='polls_answer_ok',
            field=models.CharField(default='-', max_length=32, verbose_name='Ответ получен'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='polls_enter_text',
            field=models.CharField(default='-', max_length=32, verbose_name='Запрос ответа на опрос'),
            preserve_default=False,
        ),
    ]
