# Generated by Django 4.0.4 on 2022-07-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledges', '0020_knowledge_polls_answer_ok_knowledge_polls_enter_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='digital_start',
            field=models.IntegerField(default=0, verbose_name='Цифровой рейтинг'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='reliable_params',
            field=models.CharField(default='-', max_length=64, verbose_name='Рейтинг надежности'),
            preserve_default=False,
        ),
    ]
