# Generated by Django 4.0.4 on 2022-07-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledges', '0021_knowledge_digital_start_knowledge_reliable_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='notifications_game_canceled',
            field=models.CharField(default='-', max_length=64, verbose_name='Игра была отменена'),
            preserve_default=False,
        ),
    ]
