# Generated by Django 4.0.4 on 2022-07-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledges', '0022_knowledge_notifications_game_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='friends_reg',
            field=models.TextField(default='-', verbose_name='Текст "Добавь друга"'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='polls_btn_send',
            field=models.CharField(max_length=32, verbose_name='Кнопка "Ответить"'),
        ),
    ]
