# Generated by Django 4.0.4 on 2022-07-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledges', '0023_knowledge_friends_reg_alter_knowledge_polls_btn_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='btn_game_friends_no',
            field=models.CharField(default='-', max_length=32, verbose_name='Кнопка "Не нужно"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='btn_game_friends_yes',
            field=models.CharField(default='-', max_length=32, verbose_name='Кнопка "Уведомить"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='msg_game_friends',
            field=models.CharField(default='-', max_length=64, verbose_name='Текст "Уведомить друзей"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='msg_game_friends_no',
            field=models.CharField(default='-', max_length=64, verbose_name='Текст "Отказался уведомить"'),
            preserve_default=False,
        ),
    ]
