# Generated by Django 4.0.4 on 2022-07-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledges', '0024_knowledge_btn_game_friends_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='reserve_percent',
            field=models.PositiveIntegerField(default=50, verbose_name='Процент резервных мест'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='digital_start',
            field=models.IntegerField(default=0, verbose_name='Цифровой рейтинг'),
        ),
    ]
