# Generated by Django 4.0.4 on 2022-07-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledges', '0025_knowledge_reserve_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='reserve_message',
            field=models.TextField(default='-', verbose_name='Текст "Есть резервные места"'),
            preserve_default=False,
        ),
    ]
