# Generated by Django 4.0.4 on 2022-07-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledges', '0026_knowledge_reserve_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='notifications_confirm',
            field=models.TimeField(default='00:00', verbose_name='Отправить подтверждение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='notifications_confirm_wait',
            field=models.TimeField(default='00:00', verbose_name='Время на подтверждение'),
            preserve_default=False,
        ),
    ]
