# Generated by Django 4.0.4 on 2022-07-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledges', '0027_knowledge_notifications_confirm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='btn_notify_game_no',
            field=models.CharField(default='-', max_length=32, verbose_name='Кнопка "Отказаться от игры"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='btn_notify_game_yes',
            field=models.CharField(default='-', max_length=32, verbose_name='Кнопка "Подтвердить участие"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='notifications_confirm_text',
            field=models.CharField(default='-', max_length=64, verbose_name='Текст "Подтвердите участие"'),
            preserve_default=False,
        ),
    ]
