# Generated by Django 4.0.4 on 2022-07-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledges', '0028_knowledge_btn_notify_game_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='notifications_confirm_text',
            field=models.TextField(verbose_name='Текст "Подтвердите участие"'),
        ),
    ]
