# Generated by Django 4.0.4 on 2022-07-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledges', '0029_alter_knowledge_notifications_confirm_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='notifications_confirm_reserve',
            field=models.TextField(default='-', verbose_name='Текст "Резервное подтверждение"'),
            preserve_default=False,
        ),
    ]
