# Generated by Django 4.0.4 on 2022-07-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledges', '0031_knowledge_is_banned_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='my_games_btn_no',
            field=models.CharField(default='-', max_length=32, verbose_name='Кнопка "Оставить запись"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='my_games_btn_yes',
            field=models.CharField(default='-', max_length=32, verbose_name='Кнопка "Уверен"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='my_games_safe_time',
            field=models.TimeField(default='00:00', verbose_name='За сколько до игры можно снять запись'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='my_games_wrong_text',
            field=models.TextField(default='-', verbose_name='Текст "Вы уверены? Рейтинг упадет"'),
            preserve_default=False,
        ),
    ]
