# Generated by Django 4.0.4 on 2022-07-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledges', '0032_knowledge_my_games_btn_no_knowledge_my_games_btn_yes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='reliable_up_games',
            field=models.PositiveIntegerField(default=2, verbose_name='Игр подряд для повышения'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='my_games_wrong_text',
            field=models.TextField(verbose_name='Текст "Рейтинг упадет"'),
        ),
    ]
