# Generated by Django 4.0.4 on 2022-07-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledges', '0033_knowledge_reliable_up_games_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='notifications_game_end',
            field=models.CharField(default='-', max_length=64, verbose_name='Игра завершилась'),
            preserve_default=False,
        ),
    ]
